//! Generated-file detection (banner scan + filename patterns) + body collapse.

const BANNER_SCAN_BYTES: usize = 2048;
const BANNERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "This file is automatically generated",
    "AUTO-GENERATED",
];

const FILENAME_PATTERNS: &[&str] = &[
    ".pb.go", ".gen.ts", ".gen.rs", "_pb2.py", ".pb.cc",
];

const EXACT_FILENAMES: &[&str] = &["bindings/index.ts"];

pub struct Detection<'a> {
    pub banner_line: &'a str,
}

pub fn detect<'a>(path: &str, content: &'a str) -> Option<Detection<'a>> {
    // Snap the scan window to the largest <= UTF-8 char boundary so we
    // never slice inside a multi-byte char (e.g. '→' or '—' straddling
    // the 2KB mark). Walks back at most 3 bytes since max UTF-8 width
    // is 4 bytes. Plain byte-indexing here would panic with
    // "byte index N is not a char boundary".
    let mut scan_end = content.len().min(BANNER_SCAN_BYTES);
    while scan_end > 0 && !content.is_char_boundary(scan_end) {
        scan_end -= 1;
    }
    let head = &content[..scan_end];

    // Case-insensitive "DO NOT EDIT" + case-sensitive others.
    let head_lower = head.to_lowercase();
    for line in head.lines() {
        let l = line.trim();
        if BANNERS.iter().any(|b| l.contains(b))
            || head_lower.contains("do not edit") && l.to_lowercase().contains("do not edit")
        {
            return Some(Detection { banner_line: line });
        }
    }

    // Filename-pattern paths fall back to the first non-blank line as the banner.
    let path_l = path.to_lowercase();
    let pattern_match = FILENAME_PATTERNS.iter().any(|p| path_l.ends_with(p))
        || EXACT_FILENAMES.iter().any(|p| path_l.ends_with(p));
    if pattern_match {
        let first_non_blank = content.lines().find(|l| !l.trim().is_empty()).unwrap_or("");
        return Some(Detection { banner_line: first_non_blank });
    }

    None
}

pub fn mark(path: &str, content: &str, hash_prefix: &str) -> Option<String> {
    let det = detect(path, content)?;
    Some(format!(
        "{}\n[GENERATED FILE — body suppressed | sha: {hash_prefix}]\n",
        det.banner_line.trim()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_at_generated_banner() {
        let content = "// @generated by protobuf\npackage foo\n";
        let d = detect("foo.go", content).unwrap();
        assert!(d.banner_line.contains("@generated"));
    }

    #[test]
    fn detects_do_not_edit_banner_case_insensitive() {
        let content = "// DO NOT EDIT - generated by tool\n";
        assert!(detect("x.ts", content).is_some());
        let lower = "// do not edit - generated\n";
        assert!(detect("x.ts", lower).is_some());
    }

    #[test]
    fn detects_via_pb_go_suffix() {
        let content = "package proto\n\nfunc x() {}\n";
        let d = detect("api.pb.go", content).unwrap();
        assert_eq!(d.banner_line, "package proto");
    }

    #[test]
    fn detects_via_bindings_path() {
        let content = "export const x = 1;\n";
        assert!(detect("frontend/src/bindings/index.ts", content).is_some());
    }

    #[test]
    fn does_not_detect_handwritten_source() {
        let content = "// Comment about generated tests\nfn main() {}\n";
        assert!(detect("src/main.rs", content).is_none());
    }

    #[test]
    fn detect_does_not_panic_on_multibyte_char_at_scan_boundary() {
        // '→' (U+2192) is 3 bytes in UTF-8. Place it so it straddles
        // BANNER_SCAN_BYTES (2048): 2046 'x' chars + '→' occupies
        // bytes 2046..2049. The naive `&content[..2048]` slice in the
        // pre-fix code panicked here.
        let mut content = "x".repeat(2046);
        content.push('→');
        content.push_str("trailing\n");
        // Sanity: ensure we actually straddle the boundary.
        assert!(!content.is_char_boundary(2048));
        // Must not panic; this file has no banner so the result is None.
        let result = detect("notes.md", &content);
        assert!(result.is_none());
    }

    #[test]
    fn detect_does_not_panic_on_em_dash_at_scan_boundary() {
        // '—' (em dash, U+2014) is also 3 bytes.
        let mut content = "y".repeat(2046);
        content.push('—');
        content.push_str("rest\n");
        assert!(!content.is_char_boundary(2048));
        let _ = detect("a.ts", &content); // must not panic
    }

    #[test]
    fn mark_replaces_body_with_banner_plus_marker() {
        let content = "// @generated by foo\nfunc x() {}\nfunc y() {}\n";
        let out = mark("a.pb.go", content, "abc123").unwrap();
        assert!(out.starts_with("// @generated by foo\n"));
        assert!(out.contains("[GENERATED FILE — body suppressed"));
        assert!(out.contains("sha: abc123"));
        assert!(!out.contains("func y"), "body should be suppressed");
    }
}
