// Auto-generated by ProjectPacker — do not edit.
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async packStart(opts: PackOptions, onEvent: TAURI_CHANNEL<ProgressEvent>) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_start", { opts, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async packCancel(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_cancel", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async packGetResult(jobId: string) : Promise<Result<PackResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_get_result", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validatePlan(planMd: string, protocolVersion: string) : Promise<Result<PlanValidation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_plan", { planMd, protocolVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async buildCombinedPrompt(planMd: string, protocolVersion: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_combined_prompt", { planMd, protocolVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show a save dialog and write `contents` to the user-chosen path.
 * 
 * The path comes from the OS save dialog, not the renderer — a compromised
 * renderer cannot supply an arbitrary path. Returns `Some(path)` on success
 * or `None` if the user cancelled.
 */
async savePackOutput(suggestedFilename: string, contents: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_pack_output", { suggestedFilename, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubSetToken(token: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_set_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubClearToken() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_clear_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubTokenStatus() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_token_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubGetUser() : Promise<Result<GithubUser, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_get_user") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubListRepos() : Promise<Result<GithubRepo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_list_repos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { code: string; message: string; details: string | null }
export type FileFound = { path: string; bytes: number }
export type GithubRepo = { id: number; name: string; fullName: string; description: string | null; htmlUrl: string; private: boolean; fork: boolean; archived: boolean; language: string | null; stargazersCount: number; pushedAt: string; defaultBranch: string; owner: GithubRepoOwner }
export type GithubRepoOwner = { login: string; avatarUrl: string }
export type GithubUser = { login: string; name: string | null; avatarUrl: string; htmlUrl: string; publicRepos: number }
export type GoalTemplate = { name: string; body: string }
export type PackFormat = "xml" | "markdown" | "plainText"
export type PackOptions = { target: PackTarget; goal: string; countTokens: boolean; tokenizerModel: string; secretScan: boolean; compress: boolean; removeComments: boolean; dedupFiles?: boolean; trimTrailingWs?: boolean; collapseBlankLines?: boolean; normalizeLineEndings?: boolean; collapseLockfiles?: boolean; collapseMinified?: boolean; markGenerated?: boolean; elideTypeOnlyExports?: boolean; maxFileSizeKb: number; respectGitignore: boolean; customIgnorePatterns: string[]; protocolVersion: string; format: PackFormat; 
/**
 * Defaulted via `serde(default)` so v0.1 settings missing this field
 * deserialize cleanly to `XmlSchema::Cxml` (the new default).
 */
xmlSchema?: XmlSchema }
/**
 * A redaction performed during the pack pipeline, surfaced in the
 * `<security_report>` block and via `PackResult.redactions`.
 * 
 * Note: deliberately omits the matched-excerpt field on the underlying
 * [`crate::secrets::Redaction`] — the security report should not reproduce
 * secrets, even partially.
 */
export type PackRedaction = { file: string; ruleId: string; line: number; byteOffset: number }
export type PackResult = { output: string; claudeCodePrompt: string; stats: PackStats; warnings: PackWarning[]; redactions: PackRedaction[] }
export type PackStats = { filesTotal: number; filesIncluded: number; filesSkipped: number; bytesTotal: number; 
/**
 * Token count under the user-selected tokenizer (`opts.tokenizer_model`),
 * summed across all included files. `None` when `count_tokens` is off.
 */
tokensTotal: number | null; 
/**
 * Per-model token counts of the joined pack content, computed via the
 * authentic tokenizer of each model family (with cl100k as a proxy for
 * Claude/Gemini, which don't ship public tokenizers). Surfaced in the
 * AI compatibility table on the result screen. `None` when
 * `count_tokens` is off, mirroring `tokens_total`.
 */
tokensPerModel: TokensPerModel | null; secretsFound: number; durationMs: number; 
/**
 * Per-phase wall-clock elapsed time. Always populated; `Option` variants
 * are `None` when the phase is skipped via `PackOptions` (e.g.
 * `secret_scan_ms` is `None` when `opts.secret_scan == false`). Use
 * `None` (not `Some(0)`) so the UI can render skipped phases as `—`
 * rather than misleading "0ms".
 */
walkMs: number; processMs: number; secretScanMs: number | null; tokenizeMs: number | null; emitMs: number; transforms: TransformReport[]; transformPhaseMs: number }
export type PackTarget = { kind: "folder"; value: string } | { kind: "github"; value: string }
export type PackWarning = { kind: WarningKind; path: string | null; message: string }
export type PlanError = { code: string; message: string }
export type PlanValidation = { ok: boolean; errors: PlanError[] }
export type Preset = { name: string; optionsJson: string }
export type ProgressEvent = { kind: "started"; job_id: string; target_label: string } | { kind: "cloning"; progress_pct: number } | { kind: "walking"; files_scanned: number } | { kind: "fileFoundBatch"; paths: FileFound[] } | { kind: "fileSkipped"; path: string; reason: SkipReason } | { kind: "tokenizing"; progress_pct: number } | { kind: "secretScanning"; progress_pct: number } | { kind: "secretHit"; path: string; secret_kind: string; line: number } | { kind: "compressing"; progress_pct: number } | { kind: "transformStart"; id: string } | { kind: "transformDone"; id: string; bytes_saved: number; files_touched: number } | { kind: "buildingOutput" } | { kind: "done"; stats: PackStats } | { kind: "error"; message: string; fatal: boolean }
export type Recent = { label: string; target: string; lastUsedIso: string }
export type Settings = { theme: Theme; defaultProtocolVersion: string; defaultTokenizerModel: string; recents: Recent[]; goalTemplates: GoalTemplate[]; presets: Preset[]; 
/**
 * Stored schema version. Defaults to 0 so settings written before the
 * migration framework existed are still readable.
 */
schemaVersion?: number }
export type SkipReason = { kind: "ignored" } | { kind: "tooLarge" } | { kind: "binary" } | { kind: "inaccessible" } | { kind: "encodingFailed" }
export type Theme = "dark" | "light"
/**
 * Tokenizer family selector for the typed API.
 * 
 * Wire mapping:
 * - `Gpt4o` → `o200k_base` (the actual GPT-4o tokenizer; matches what
 * `count_by_name("gpt-4o-mini")` returns, so the per-file `tokens_total`
 * summed against `gpt-4o-mini` agrees with `tokens_per_model.gpt4o`
 * modulo the join-overhead between files).
 * - `Claude` → `cl100k_base` (Anthropic's tokenizer is unpublished;
 * cl100k is the closest public approximation).
 * - `GeminiApprox` → `o200k_base` count multiplied by 1.05 and rounded up;
 * Gemini ships no public tokenizer so this is a deliberate over-estimate
 * on top of GPT-4o's encoder.
 * - `Llama3`, `Qwen2_5`, `DeepSeek`, `Mistral` → vendored HuggingFace
 * `tokenizer.json` blobs, parsed lazily on first use (Phase 2 T2).
 */
export type TokenModel = "gpt4o" | "claude" | "llama3" | "qwen2_5" | "deepSeek" | "mistral" | "geminiApprox"
/**
 * All seven per-model token counts for a single input.
 * 
 * Returned by [`count_all`]; mirrors the rows in the AI compatibility table.
 * The wire-format field names match [`TokenModel`]'s variant strings so
 * frontends can subscript with `tokensPerModel[tokenModel]` at type-check
 * time. See `frontend/src/routes/Pack.tsx` for the consumer side.
 */
export type TokensPerModel = { gpt4o: number; claude: number; llama3: number; qwen2_5: number; deepSeek: number; mistral: number; geminiApprox: number }
export type TransformReport = { id: string; bytesSaved: number; filesTouched: number; elapsedMs: number }
export type WarningKind = { kind: "fileSkipped" } | { kind: "treeSitterFailed" } | { kind: "gitLogMissing" } | { kind: "encodingFallback" } | { kind: "secretScanFailed" } | { kind: "tokenizeFailed" } | { kind: "transformFailed" }
export type XmlSchema = "cxml" | "legacy"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
