// Auto-generated by ProjectPacker — do not edit.
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async packStart(opts: PackOptions) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_start", { opts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async packCancel(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_cancel", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async packGetResult(jobId: string) : Promise<Result<PackResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_get_result", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validatePlan(planMd: string, protocolVersion: string) : Promise<Result<PlanValidation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_plan", { planMd, protocolVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async buildCombinedPrompt(planMd: string, protocolVersion: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_combined_prompt", { planMd, protocolVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveToFile(path: string, contents: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_to_file", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { code: string; message: string; details: string | null }
export type FileFound = { path: string; bytes: number }
export type GoalTemplate = { name: string; body: string }
export type PackFormat = "xml" | "markdown" | "plainText"
export type PackOptions = { target: PackTarget; goal: string; includeGitHistory: boolean; countTokens: boolean; tokenizerModel: string; secretScan: boolean; compress: boolean; removeComments: boolean; maxFileSizeKb: number; respectGitignore: boolean; customIgnorePatterns: string[]; protocolVersion: string; format: PackFormat }
export type PackResult = { output: string; claudeCodePrompt: string; stats: PackStats; warnings: PackWarning[] }
export type PackStats = { filesTotal: number; filesIncluded: number; filesSkipped: number; bytesTotal: number; tokensTotal: number | null; secretsFound: number; durationMs: number }
export type PackTarget = { kind: "folder"; value: string } | { kind: "github"; value: string }
export type PackWarning = { kind: WarningKind; path: string | null; message: string }
export type PlanError = { code: string; message: string }
export type PlanValidation = { ok: boolean; errors: PlanError[] }
export type Preset = { name: string; optionsJson: string }
export type ProgressEvent = { kind: "started"; job_id: string; target_label: string } | { kind: "cloning"; progress_pct: number } | { kind: "walking"; files_scanned: number } | { kind: "fileFoundBatch"; paths: FileFound[] } | { kind: "fileSkipped"; path: string; reason: SkipReason } | { kind: "tokenizing"; progress_pct: number } | { kind: "secretScanning"; progress_pct: number } | { kind: "secretHit"; path: string; secret_kind: string; line: number } | { kind: "compressing"; progress_pct: number } | { kind: "buildingOutput" } | { kind: "done"; stats: PackStats } | { kind: "error"; message: string; fatal: boolean }
export type Recent = { label: string; target: string; lastUsedIso: string }
export type Settings = { theme: Theme; defaultProtocolVersion: string; defaultTokenizerModel: string; recents: Recent[]; goalTemplates: GoalTemplate[]; presets: Preset[] }
export type SkipReason = { kind: "ignored" } | { kind: "tooLarge" } | { kind: "binary" } | { kind: "inaccessible" } | { kind: "encodingFailed" }
export type Theme = "dark" | "light"
export type WarningKind = { kind: "fileSkipped" } | { kind: "treeSitterFailed" } | { kind: "gitLogMissing" } | { kind: "encodingFallback" } | { kind: "secretScanFailed" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
