// Auto-generated by ProjectPacker — do not edit.
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async packStart(opts: PackOptions, onEvent: TAURI_CHANNEL<ProgressEvent>) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_start", { opts, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async packCancel(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_cancel", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async packGetResult(jobId: string) : Promise<Result<PackResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_get_result", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validatePlan(planMd: string, protocolVersion: string) : Promise<Result<PlanValidation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_plan", { planMd, protocolVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async buildCombinedPrompt(planMd: string, protocolVersion: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_combined_prompt", { planMd, protocolVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveToFile(path: string, contents: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_to_file", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { code: string; message: string; details: string | null }
export type FileFound = { path: string; bytes: number }
export type GoalTemplate = { name: string; body: string }
export type PackFormat = "xml" | "markdown" | "plainText"
export type PackOptions = { target: PackTarget; goal: string; includeGitHistory: boolean; countTokens: boolean; tokenizerModel: string; secretScan: boolean; compress: boolean; removeComments: boolean; maxFileSizeKb: number; respectGitignore: boolean; customIgnorePatterns: string[]; protocolVersion: string; format: PackFormat; 
/**
 * Defaulted via `serde(default)` so v0.1 settings missing this field
 * deserialize cleanly to `XmlSchema::Cxml` (the new default).
 */
xmlSchema?: XmlSchema }
/**
 * A redaction performed during the pack pipeline, surfaced in the
 * `<security_report>` block and via `PackResult.redactions`.
 * 
 * Note: deliberately omits the matched-excerpt field on the underlying
 * [`crate::secrets::Redaction`] — the security report should not reproduce
 * secrets, even partially.
 */
export type PackRedaction = { file: string; ruleId: string; line: number; byteOffset: number }
export type PackResult = { output: string; claudeCodePrompt: string; stats: PackStats; warnings: PackWarning[]; redactions: PackRedaction[] }
export type PackStats = { filesTotal: number; filesIncluded: number; filesSkipped: number; bytesTotal: number; 
/**
 * Token count under the user-selected tokenizer (`opts.tokenizer_model`),
 * summed across all included files. `None` when `count_tokens` is off.
 */
tokensTotal: number | null; 
/**
 * Per-model token counts of the joined pack content, computed via the
 * authentic tokenizer of each model family (with cl100k as a proxy for
 * Claude/Gemini, which don't ship public tokenizers). Surfaced in the
 * AI compatibility table on the result screen. `None` when
 * `count_tokens` is off, mirroring `tokens_total`.
 */
tokensPerModel: TokensPerModel | null; secretsFound: number; durationMs: number }
export type PackTarget = { kind: "folder"; value: string } | { kind: "github"; value: string }
export type PackWarning = { kind: WarningKind; path: string | null; message: string }
export type PlanError = { code: string; message: string }
export type PlanValidation = { ok: boolean; errors: PlanError[] }
export type Preset = { name: string; optionsJson: string }
export type ProgressEvent = { kind: "started"; job_id: string; target_label: string } | { kind: "cloning"; progress_pct: number } | { kind: "walking"; files_scanned: number } | { kind: "fileFoundBatch"; paths: FileFound[] } | { kind: "fileSkipped"; path: string; reason: SkipReason } | { kind: "tokenizing"; progress_pct: number } | { kind: "secretScanning"; progress_pct: number } | { kind: "secretHit"; path: string; secret_kind: string; line: number } | { kind: "compressing"; progress_pct: number } | { kind: "buildingOutput" } | { kind: "done"; stats: PackStats } | { kind: "error"; message: string; fatal: boolean }
export type Recent = { label: string; target: string; lastUsedIso: string }
/**
 * One redacted span discovered during a scan. Offsets refer to the
 * **original** (pre-redaction) content so callers can correlate against
 * the source.
 */
export type Redaction = { 
/**
 * Stable gitleaks rule id (e.g. `"aws-access-token"`).
 */
ruleId: string; 
/**
 * 1-based line number in the original content.
 */
line: number; 
/**
 * 0-based byte offset in the original content where the redaction
 * begins.
 */
byteOffset: number; 
/**
 * First 4 + last 4 chars of the matched substring with `***` in
 * between (or `***` for short matches).
 */
matchedExcerpt: string }
export type Settings = { theme: Theme; defaultProtocolVersion: string; defaultTokenizerModel: string; recents: Recent[]; goalTemplates: GoalTemplate[]; presets: Preset[] }
export type SkipReason = { kind: "ignored" } | { kind: "tooLarge" } | { kind: "binary" } | { kind: "inaccessible" } | { kind: "encodingFailed" }
export type Theme = "dark" | "light"
/**
 * Tokenizer family selector for the typed API.
 * 
 * Wire mapping:
 * - `Gpt4o`, `Claude` → `cl100k_base` (Anthropic's tokenizer behaves close
 * enough to cl100k that we share the encoder).
 * - `GeminiApprox` → `cl100k_base` count multiplied by 1.05 and rounded up;
 * Gemini ships no public tokenizer so this is a deliberate over-estimate.
 * - `Llama3`, `Qwen2_5`, `DeepSeek`, `Mistral` → vendored HuggingFace
 * `tokenizer.json` blobs, parsed lazily on first use (Phase 2 T2).
 */
export type TokenModel = "gpt4o" | "claude" | "llama3" | "qwen2_5" | "deepSeek" | "mistral" | "geminiApprox"
/**
 * All seven per-model token counts for a single input.
 * 
 * Returned by [`count_all`]; mirrors the rows in the AI compatibility table.
 * The wire-format field names match [`TokenModel`]'s variant strings so
 * frontends can subscript with `tokensPerModel[tokenModel]` at type-check
 * time. See `frontend/src/routes/Pack.tsx` for the consumer side.
 */
export type TokensPerModel = { gpt4o: number; claude: number; llama3: number; qwen2_5: number; deepSeek: number; mistral: number; geminiApprox: number }
export type WarningKind = { kind: "fileSkipped" } | { kind: "treeSitterFailed" } | { kind: "gitLogMissing" } | { kind: "encodingFallback" } | { kind: "secretScanFailed" }
export type XmlSchema = "cxml" | "legacy"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
